### ISSUE TITLE
Sort out the README

### ISSUE THREAD

**Issue by rossbruniges** [mozilla/source#133]
A few things can be tweeked to make it a bit more user-friendly in regard to getting things set up locally.

Creating the virtualenv is rather important (as is the initial create command as we need to ensure that site-packages aren't include and python 2.6 is define - it's a HARD dependency I think) so should probably outline that a bit more.

**Comment by slifty** [comment]
Two issues:

1) line git clone --recursive git@github:{you}/source.git

should probably be

git clone --recursive git@github.com:{you}/source.git

(added .com)

2) on pip install -r requirements/dev.txt I now get the following error:

Downloading/unpacking MySQL-python==1.2.3c1 (from -r
requirements/../vendor/src/funfactory/funfactory/requirements/compiled.txt
(line 1))
  Downloading MySQL-python-1.2.3c1.tar.gz (89kB): 89kB downloaded
  Running setup.py egg_info for package MySQL-python
    sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File
"/Users/slifty/Dropbox/Code/python/source/venv/build/MySQL-python/setup.py",
line 15, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 24, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    Complete output from command python setup.py egg_info:
    sh: mysql_config: command not found

Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File
"/Users/slifty/Dropbox/Code/python/source/venv/build/MySQL-python/setup.py",
line 15, in <module>

```
metadata, options = get_config()
```

  File "setup_posix.py", line 43, in get_config

```
libs = mysql_config("libs_r")
```

  File "setup_posix.py", line 24, in mysql_config

```
raise EnvironmentError("%s not found" % (mysql_config.path,))
```

EnvironmentError: mysql_config not found

---

Command python setup.py egg_info failed with error code 1 in
/Users/slifty/Dropbox/Code/python/source/venv/build/MySQL-python
Storing complete log in /Users/slifty/.pip/pip.log

**Comment by slifty** [comment]
I do have mysql installed.  (running this on OSX).  However, I have nothing
set up to link Python and MySQL.

I'll dig around a bit.

**Comment by slifty** [comment]
It fell into backlog; I'll give this another try next week.
